version: 2.1
orbs:
  python: circleci/python@2.0.3

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox



jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - *prepare_venv
      - *prepare_tox
      -  run:
            name: Runnning app tests
            command: |
              tox

workflows:
  test_my_app:
    jobs:
      - build_and_test
